### ISSUE TITLE
Possible permissions error on tmp when using nib console <service>

### ISSUE THREAD

**Issue by scotthelm** [technekes/nib#62]
The following is output I received when attempting to console to a service that already had a tmp dir.

```
apps/path $ nib console web
mkdir: can't create directory '/apps/path/tmp': File exists
Starting client_web_bundle_1
[1] pry(main)> Model.first
--- ERROR REPORT TEMPLATE -------------------------------------------------------
- What did you do?

  I ran the command `/usr/local/bundle/bin/bundle `

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...


Error details

    Errno::ENOTDIR: Not a directory @ rb_sysopen - /usr/src/app/tmp/irb_history
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/history.rb:114:in `initialize'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/history.rb:114:in `open'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/history.rb:114:in `history_file'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/history.rb:106:in `save_to_file'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/history.rb:50:in `call'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/history.rb:50:in `push'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/pry_instance.rb:267:in `handle_line'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `catch'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `block in eval'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `catch'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `eval'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/repl.rb:77:in `block in repl'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/repl.rb:67:in `loop'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/repl.rb:67:in `repl'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/repl.rb:38:in `block in start'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/input_lock.rb:61:in `__with_ownership'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/input_lock.rb:79:in `with_ownership'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/repl.rb:38:in `start'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/repl.rb:15:in `start'
      /usr/local/bundle/gems/pry-0.10.1/lib/pry/pry_class.rb:169:in `start'
      /usr/local/bundle/gems/pry-nav-0.2.4/lib/pry-nav/pry_ext.rb:17:in `start_with_pry_nav'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/cli/console.rb:15:in `run'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/cli.rb:333:in `console'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
      /usr/local/bundle/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
      /usr/local/bundle/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
      /usr/local/bundle/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
      /usr/local/bundle/bin/bundle:22:in `load'
      /usr/local/bundle/bin/bundle:22:in `<main>'

Environment

  Bundler   1.12.5
  Rubygems  2.6.4
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /usr/local/bundle
  GEM_PATH
  Git       2.1.4

      Bundler settings

  console
    Set for the current user (/root/.bundle/config): "pry"
  jobs
    Set for your local app (/usr/local/bundle/config): "4"
  disable_shared_gems
    Set for your local app (/usr/local/bundle/config): "true"
  app_config
    Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
  bin
    Set via BUNDLE_BIN: "/usr/local/bundle/bin"
  path
    Set via BUNDLE_PATH: "/usr/local/bundle"
  silence_root_warning
    Set via BUNDLE_SILENCE_ROOT_WARNING: "1"
  orig_path
    Set via BUNDLE_ORIG_PATH: "/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  bin_path
    Set via BUNDLE_BIN_PATH: "/usr/local/bundle/gems/bundler-1.12.5/exe/bundle"
  gemfile
    Set via BUNDLE_GEMFILE: "/usr/src/app/Gemfile"
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/bundler/bundler/search?q=Not+a+directory+%40+rb_sysopen+-+%2Fusr%2Fsrc%2Fapp%2Ftmp%2Firb_history&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/bundler/bundler/issues/new
```

**Comment by johnallen3d** [comment]
Hello @scotthelm, has this persisted as an issue?

**Comment by scotthelm** [comment]
This was user error. I had a FILE called tmp. I did not recognize the difference when performing my `ls`. I am closing this issue.
